blueprint:
  name: "IKEA Bilresa Scroll Wheel – Volume Control (Right & Left)"
  description: "Control media player volume using IKEA Bilresa scroll wheel (right = up, left = down)"
  domain: automation

  input:
    scrollwheel_right_event_entity:
      name: "Scroll Wheel Event Entity – Right Rotation"
      description: "Event entity fired when rotating right"
      selector:
        entity:
          domain: event

    scrollwheel_left_event_entity:
      name: "Scroll Wheel Event Entity – Left Rotation"
      description: "Event entity fired when rotating left"
      selector:
        entity:
          domain: event

    target_media_player:
      name: "Target Media Player"
      description: "Media player to control volume"
      selector:
        entity:
          domain: media_player

    volume_per_step_right:
      name: "Volume per Step – Right (%)"
      description: "How much volume to increase per step"
      default: 5
      selector:
        number:
          min: 1
          max: 20

    volume_per_step_left:
      name: "Volume per Step – Left (%)"
      description: "How much volume to decrease per step"
      default: 5
      selector:
        number:
          min: 1
          max: 20

trigger:
  - platform: state
    entity_id: !input scrollwheel_right_event_entity
    id: right_scroll

  - platform: state
    entity_id: !input scrollwheel_left_event_entity
    id: left_scroll

action:
  - variables:
      is_right_scroll: "{{ trigger.id == 'right_scroll' }}"
      target_entity: !input target_media_player

      # Blueprint input values must be explicitly assigned
      volume_step_right: !input volume_per_step_right
      volume_step_left: !input volume_per_step_left

      # Direction: Right = +1, Left = -1
      direction: "{{ 1 if is_right_scroll else -1 }}"

      # Pick correct step size
      volume_step: "{{ volume_step_right if is_right_scroll else volume_step_left }}"

      # Scroll count (fallback to 1 if missing or empty)
      press_count: "{{ trigger.to_state.attributes.totalNumberOfPressesCounted | default(1) | int }}"

      # Current volume (0.0–1.0)
      current_volume: "{{ state_attr(target_entity, 'volume_level') | float(0) }}"

      # Volume change (as fraction)
      volume_change: "{{ (volume_step | int * press_count * direction) / 100 }}"

      # Clamp new volume to 0.0–1.0
      new_volume: >-
        {% set v = current_volume + volume_change %}
        {% if v < 0 %}
          0
        {% elif v > 1 %}
          1
        {% else %}
          {{ v }}
        {% endif %}

  - service: media_player.volume_set
    target:
      entity_id: !input target_media_player
    data:
      volume_level: "{{ new_volume }}"

mode: queued
max: 20
