blueprint:
  name: IKEA BILRESA – Matter Button
  description: >
    IKEA BILRESA button via Matter over Thread.
    Supports 1×, 2×, 3× and long press.
  domain: automation

  input:
    button_event:
      name: Button Event Entity
      selector:
        entity:
          domain: event

    action_single:
      name: 1× Press Action
      default: []
      selector:
        action: {}

    action_double:
      name: 2× Press Action
      default: []
      selector:
        action: {}

    action_triple:
      name: 3× Press Action
      default: []
      selector:
        action: {}

    action_long:
      name: Long Press Action
      default: []
      selector:
        action: {}

mode: single

trigger:
  - platform: state
    entity_id: !input button_event
    attribute: event_type

action:
  - choose:
      - conditions: "{{ trigger.to_state.attributes.event_type == 'multi_press_1' }}"
        sequence: !input action_single

      - conditions: "{{ trigger.to_state.attributes.event_type == 'multi_press_2' }}"
        sequence: !input action_double

      - conditions: "{{ trigger.to_state.attributes.event_type == 'multi_press_3' }}"
        sequence: !input action_triple

      - conditions: "{{ trigger.to_state.attributes.event_type == 'long_press' }}"
        sequence: !input action_long
